stages:
  parse_labels:
    cmd: bohr parse-labels
    deps:
    - labels
    outs:
    - labels.py:
        cache: false
  preprocess_bugginess_train:
    cmd: 7z x downloaded-data/bugginess_train.7z -odata/bugginess
    deps:
    - downloaded-data/bugginess_train.7z
    outs:
    - data/bugginess/train/bug_sample.csv:
        cache: false
    - data/bugginess/train/bug_sample_files.csv:
        cache: false
    - data/bugginess/train/bug_sample_issues.csv:
        cache: false
  preprocess_bugginess_test:
    cmd: cp downloaded-data/{1151-commits.csv,berger.csv,herzig.csv} data/bugginess/test
    deps:
    - downloaded-data/1151-commits.csv
    - downloaded-data/berger.csv
    - downloaded-data/herzig.csv
    outs:
    - data/bugginess/test/1151-commits.csv
    - data/bugginess/test/berger.csv
    - data/bugginess/test/herzig.csv
  preprocess_smells:
    cmd: bash data-preprocessing/smells.sh
    deps:
    - data-preprocessing/smells.sh
    - downloaded-data/smells-madeyski.csv
    outs:
    - data/smells/test.csv
    - data/smells/train.csv
  bugginess-1k_label_dataset:
    cmd: bohr label-dataset bugginess-1k bugginess-train-1k
    deps:
    - data/bugginess/train/bug_sample.csv
    - data/bugginess/train/bug_sample_files.csv
    - data/bugginess/train/bug_sample_issues.csv
    - dataloaders/bugginess-train-1k.py
    - generated/bugginess-1k/heuristic_matrix_train.pkl
    - tasks/bugginess-1k.py
    outs:
    - labeled-data/bugginess-1k.csv
  smells_10_label_dataset:
    cmd: bohr label-dataset smells_10 smells-train_10
    deps:
    - data/smells/train.csv
    - dataloaders/smells-train_10.py
    - generated/smells_10/heuristic_matrix_train.pkl
    - tasks/smells_10.py
    outs:
    - labeled-data/smells_10.csv
  bugginess-1k_apply_heuristics:
    cmd: bohr apply-heuristics bugginess-1k
    deps:
    - data/bugginess/test/1151-commits.csv
    - data/bugginess/test/berger.csv
    - data/bugginess/train/bug_sample.csv
    - data/bugginess/train/bug_sample_files.csv
    - data/bugginess/train/bug_sample_issues.csv
    - dataloaders/1151-commits.py
    - dataloaders/berger.py
    - dataloaders/bugginess-train-1k.py
    - heuristics
    - labels.py
    - tasks/bugginess-1k.py
    outs:
    - generated/bugginess-1k/analysis_1151-commits.csv:
        cache: false
    - generated/bugginess-1k/analysis_berger.csv:
        cache: false
    - generated/bugginess-1k/analysis_train.csv:
        cache: false
    - generated/bugginess-1k/heuristic_matrix_1151-commits.pkl
    - generated/bugginess-1k/heuristic_matrix_berger.pkl
    - generated/bugginess-1k/heuristic_matrix_train.pkl
    metrics:
    - metrics/bugginess-1k/analysis_1151-commits.json:
        cache: false
    - metrics/bugginess-1k/analysis_berger.json:
        cache: false
    - metrics/bugginess-1k/analysis_train.json:
        cache: false
    - metrics/bugginess-1k/heuristic_metrics.json:
        cache: false
  bugginess-1k_train_label_model:
    cmd: bohr train-label-model bugginess-1k
    deps:
    - data/bugginess/test/1151-commits.csv
    - data/bugginess/test/berger.csv
    - dataloaders/1151-commits.py
    - dataloaders/berger.py
    - generated/bugginess-1k/heuristic_matrix_1151-commits.pkl
    - generated/bugginess-1k/heuristic_matrix_berger.pkl
    - generated/bugginess-1k/heuristic_matrix_train.pkl
    - tasks/bugginess-1k.py
    outs:
    - generated/bugginess-1k/label_model.pkl
    metrics:
    - metrics/bugginess-1k/label_model_metrics.json:
        cache: false
  smells_10_apply_heuristics:
    cmd: bohr apply-heuristics smells_10
    deps:
    - data/smells/test.csv
    - data/smells/train.csv
    - dataloaders/smells-test_10.py
    - dataloaders/smells-train_10.py
    - heuristics
    - labels.py
    - tasks/smells_10.py
    outs:
    - generated/smells_10/analysis_smells-test_10.csv:
        cache: false
    - generated/smells_10/analysis_train.csv:
        cache: false
    - generated/smells_10/heuristic_matrix_smells-test_10.pkl
    - generated/smells_10/heuristic_matrix_train.pkl
    metrics:
    - metrics/smells_10/analysis_smells-test_10.json:
        cache: false
    - metrics/smells_10/analysis_train.json:
        cache: false
    - metrics/smells_10/heuristic_metrics.json:
        cache: false
  smells_10_train_label_model:
    cmd: bohr train-label-model smells_10
    deps:
    - data/smells/test.csv
    - dataloaders/smells-test_10.py
    - generated/smells_10/heuristic_matrix_smells-test_10.pkl
    - generated/smells_10/heuristic_matrix_train.pkl
    - tasks/smells_10.py
    outs:
    - generated/smells_10/label_model.pkl
    metrics:
    - metrics/smells_10/label_model_metrics.json:
        cache: false
